### ISSUE TITLE
java ditto-client threads leakage

### ISSUE THREAD

**Issue by desislava-marinova** [eclipse/ditto-clients#87]
Steps executed:

- Open java ditto-client
- call registerForThingChanges
- destroy the client

Every DittoClients seems to occupy ~10 threads in this scenario
When all clients are destroyed, the following threads are still open

| Number of opened clients | Number of opened threads | Number of ditto-client--adaptable-bus threads after destroy| Number of pool-X-thread-Y threads after destroy|
| ------------- | ------------- | ------------- | ------------- |
| 10  | 102 | 22 | 10 |
| 20  | 202 | 42 | 20 |
| 100  | 1002 | 202 | 100 |

The district thread stacks are as follow (if needed I can upload the whole stack trace)

```
"ditto-client--adaptable-bus-74ef6b92-2a09-4b4f-ad24-c3b3689880c7-1" Id=1406 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f5ac102
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f5ac102
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"ditto-client--adaptable-bus-0d61b4fa-984c-4bdf-abf0-f06f951e78f8-2" Id=1396 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@895416d
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@895416d
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"pool-99-thread-1" Id=1394 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71a06021
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71a06021
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by desislava-marinova** [comment]
The problem described above is only when no events are received at all. If there are events the number of leaked threads is a lot more.
